services:
  sofort.manager.routes:
    class: Sofort\Manager\SofortRoutesManager
  sofort.manager:
    class: Sofort\Manager\SofortManager
    arguments: [@event_dispatcher, @sofort.manager.routes, @validator]
